Repository NeoWaita/NeoWaita, pull requests merged in 2024-09, with the labels that each got.

#2 Add Librewolf icons + Bitwig Studio MIME file icons
  apps/scalable/io.gitlab.librewolf-community.svg
  apps/scalable/librewolf.svg
  apps/scalable/meson.build
  apps/symbolic/io.gitlab.librewolf-community-symbolic.svg
  apps/symbolic/librewolf-symbolic.svg
  apps/symbolic/meson.build
  mimes/scalable/application-x-bitwig-studio.svg
  mimes/scalable/application-x-com.bitwig.BitwigStudio.svg
  mimes/scalable/meson.build
Labels: enhancement

#27 replace all the reference of morewaita with neowaita
  AUTHORS
  PACKAGING.md
  README.md
  index.theme
  install.sh
  meson.build
Labels: community issue

#19 add librewolf, bitwig icons and mimetypes by Yoiannides
  mimes/scalable/application-bitwig-project.svg
  mimes/scalable/application-bitwig-template.svg
  mimes/scalable/application-x-bitwig-project.svg
  mimes/scalable/application-x-bitwig-template.svg
  mimes/scalable/meson.build
Labels: enhancement, high priority
